# Generated by Django 5.0.6 on 2024-05-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Post',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='star_given',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='review',
            table=None,
        ),
    ]
